### ISSUE TITLE
Plugin fails to install 

### ISSUE THREAD

**Issue by DiabloPinata** [maributt/FPSLimiter#1]
Whenever I try to install the plugin through the Plugin Installer, it gives me a "Failed to Install" error with no other information.

**Comment by maributt** [comment]
Honestly no clue why it does that, I'm getting the same error, will try to fix it whenever I have the time, for now you can totally just download the zip and load it manually from your /xlsettings experimental tab by giving it a path to where the dll file is on your computer, hope this helps o7
