### ISSUE TITLE
Installer error

### ISSUE THREAD

**Issue by ahhlec** [maributt/fpslimiter#2]
Failed to install plugin FPSLimiter after installing https://raw.githubusercontent.com/maributt/xivplugins/main/repo.json into my custom plugin repository. Restarting the game did not solve this issue.

![image](https://user-images.githubusercontent.com/77597674/180062951-d646b869-c8cf-4c26-b176-f7b98b5138b5.png)

**Comment by maributt** [comment]
This issue should now be fixed, please try reinstalling and let me know if all goes well!
