### ISSUE TITLE
[feature request] Enabled in character selection

### ISSUE THREAD

**Issue by drejjmit** [maributt/fpslimiter#3]
Would it be possible to have the plugin loaded in character selection? I often keep it in character selection while waiting on retainers etc. 
Would be great if your plugin could be loaded there too. I don't need 60fps there wasting resources. At least the BG option?

**Comment by maributt** [comment]
Sure thing, I just pushed an update for this, let me know if everything works as expected!
You can use `/fps` to open up the new config menu.
